# Core configuration for SilkC system
# DO NOT CHANGE THIS
name: SilkCore
version: 1.2.0-alpha
frontend_version: 1.3-alpha
config_version: 2.0-indev

# System-wide settings
environment:
  log_level: VERBOSE
  # Options for log level:
  # INFO displays only important messages and user friendly information such has fatal errors and steps to solve
  # DEBUG displays all messages including debug information useful for developers
  # VERBOSE displays all messages including debug information and detailed operational information
  # QUIET is perfect for prod and shows nothing except fatal errors
  env_file: ".env"